import { Hono } from 'hono'
import { cors } from 'hono/cors'
import { PrismaClient } from '@prisma/client'
import bcrypt from 'bcryptjs'
import { SignJWT, jwtVerify } from 'jose'
import { runAgent } from './runtime'
import { streamAgent } from './stream-agent'
import { executeTool, getTool, listTools } from './tools'
import { getUsage } from './usage'
import { generateApiKey } from './keys'
import { resolveApproval } from './approvals'
import { searchMemory } from './memory-api'
import { retrieveMemory, saveMemory } from './rag'
import { rateLimit, rateLimitKey } from './rate-limit'
import { validateToolPermission } from './policy'

const app = new Hono().basePath('/api')
const globalForPrisma = globalThis as unknown as { prisma?: PrismaClient }
function db() { if (!process.env.DATABASE_URL) return null; if (!globalForPrisma.prisma) globalForPrisma.prisma = new PrismaClient(); return globalForPrisma.prisma }
function jwtSecret() { const value = process.env.JWT_SECRET; if (!value || value.length < 32) throw new Error('JWT_SECRET must be configured with at least 32 characters'); return new TextEncoder().encode(value) }
async function signToken(payload: { sub: string; email: string }) { return new SignJWT(payload).setProtectedHeader({ alg: 'HS256' }).setIssuedAt().setExpirationTime('7d').sign(jwtSecret()) }
async function verifyToken(token: string) { const { payload } = await jwtVerify(token, jwtSecret()); if (typeof payload.sub !== 'string' || typeof payload.email !== 'string') throw new Error('invalid_token'); return payload as { sub: string; email: string } }
function authToken(c: any) { const value = c.req.header('authorization') || ''; return value.startsWith('Bearer ') ? value.slice(7) : '' }
async function requireUser(c: any) { const prisma = db(); if (!prisma) throw new Error('DATABASE_NOT_CONFIGURED'); const token = authToken(c); if (!token) throw new Error('UNAUTHORIZED'); const payload = await verifyToken(token); const user = await prisma.user.findUnique({ where: { id: payload.sub }, include: { tenants: true } }); if (!user || !user.isActive) throw new Error('UNAUTHORIZED'); return { prisma, user, tenant: user.tenants[0] } }
function limited(c: any, scope: string, limit = 60) { const r = rateLimit(rateLimitKey(c, scope), limit); return r }
const configuredOrigins = (process.env.CORS_ORIGINS || '').split(',').map((s) => s.trim()).filter(Boolean)
app.use('*', cors({ origin: (origin) => { if (!origin) return configuredOrigins[0] || ''; if (configuredOrigins.includes(origin)) return origin; return '' }, credentials: true }))
app.get('/', (c) => c.json({ name: 'AI Agent Manager API', version: '0.8.0', status: 'ok', runtime: 'vercel' }))
app.get('/health', async (c) => { const prisma = db(); if (!prisma) return c.json({ status: 'ok', database: 'not_configured' }); try { await prisma.$queryRaw`SELECT 1`; return c.json({ status: 'ok', database: 'connected', time: new Date().toISOString() }) } catch (e: any) { return c.json({ status: 'degraded', database: 'error', error: e?.message || 'db_error' }, 503) } })
app.post('/auth/register', async (c) => { const rl = limited(c, 'register', 10); if (!rl.allowed) return c.json({ error: 'RATE_LIMITED', retryAfter: rl.retryAfter }, 429); const prisma = db(); if (!prisma) return c.json({ error: 'DATABASE_NOT_CONFIGURED' }, 503); let body: any; try { body = await c.req.json() } catch { return c.json({ error: 'INVALID_JSON' }, 400) }; const email = String(body.email || '').trim().toLowerCase(), password = String(body.password || ''), name = body.name ? String(body.name).trim().slice(0, 120) : null; if (!/^\S+@\S+\.\S+$/.test(email) || password.length < 6 || password.length > 128) return c.json({ error: 'INVALID_INPUT' }, 400); try { if (await prisma.user.findUnique({ where: { email } })) return c.json({ error: 'EMAIL_ALREADY_EXISTS' }, 409); const passwordHash = await bcrypt.hash(password, 12); const user = await prisma.user.create({ data: { email, passwordHash, name, tenants: { create: { name: name || email.split('@')[0], slug: `t-${Date.now().toString(36)}`, plan: 'FREE', credits: 100 } } }, include: { tenants: true } }); const token = await signToken({ sub: user.id, email }); const tenant = user.tenants[0]; return c.json({ token, user: { id: user.id, email, name: user.name, role: user.role }, tenant: tenant ? { id: tenant.id, name: tenant.name, credits: tenant.credits, plan: tenant.plan } : null }) } catch (e) { console.error(e); return c.json({ error: 'REGISTER_FAILED' }, 500) } })
app.post('/auth/login', async (c) => { const rl = limited(c, 'login', 20); if (!rl.allowed) return c.json({ error: 'RATE_LIMITED', retryAfter: rl.retryAfter }, 429); const prisma = db(); if (!prisma) return c.json({ error: 'DATABASE_NOT_CONFIGURED' }, 503); let body: any; try { body = await c.req.json() } catch { return c.json({ error: 'INVALID_JSON' }, 400) }; const email = String(body.email || '').trim().toLowerCase(), password = String(body.password || ''); try { const user = await prisma.user.findUnique({ where: { email }, include: { tenants: true } }); if (!user || !user.passwordHash || !(await bcrypt.compare(password, user.passwordHash))) return c.json({ error: 'INVALID_CREDENTIALS' }, 401); const token = await signToken({ sub: user.id, email }); const tenant = user.tenants[0]; return c.json({ token, user: { id: user.id, email, name: user.name, role: user.role }, tenant: tenant ? { id: tenant.id, name: tenant.name, credits: tenant.credits, plan: tenant.plan } : null }) } catch (e) { console.error(e); return c.json({ error: 'LOGIN_FAILED' }, 500) } })
app.get('/auth/me', async (c) => { try { const { user, tenant } = await requireUser(c); return c.json({ user: { id: user.id, email: user.email, name: user.name, role: user.role, isAdmin: user.role === 'ADMIN' }, tenant: tenant ? { id: tenant.id, name: tenant.name, credits: tenant.credits, plan: tenant.plan } : null }) } catch (e: any) { return c.json({ error: e?.message === 'UNAUTHORIZED' ? 'UNAUTHORIZED' : 'AUTH_FAILED' }, 401) } })
app.post('/agents', async (c) => { try { const { prisma, tenant } = await requireUser(c); if (!tenant) return c.json({ error: 'TENANT_NOT_FOUND' }, 404); let body: any; try { body = await c.req.json() } catch { return c.json({ error: 'INVALID_JSON' }, 400) }; const name = String(body.name || '').trim(); const slug = String(body.slug || name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')); if (!name || !slug) return c.json({ error: 'INVALID_INPUT' }, 400); const agent = await prisma.agent.create({ data: { tenantId: tenant.id, name, slug, description: body.description ? String(body.description) : null, systemPrompt: body.systemPrompt ? String(body.systemPrompt) : null, tools: Array.isArray(body.tools) ? body.tools.map(String) : [], permissions: Array.isArray(body.permissions) ? body.permissions.map(String) : [], riskLevel: body.riskLevel ? String(body.riskLevel) : 'LOW', approvalPolicy: body.approvalPolicy ? String(body.approvalPolicy) : 'AUTO' } }); return c.json({ agent }, 201) } catch (e: any) { return c.json({ error: e?.message || 'AGENT_CREATE_FAILED' }, 400) } })
app.get('/agents', async (c) => { try { const { prisma, tenant } = await requireUser(c); if (!tenant) return c.json({ agents: [] }); return c.json({ agents: await prisma.agent.findMany({ where: { tenantId: tenant.id }, orderBy: { createdAt: 'desc' } }) }) } catch (e: any) { return c.json({ error: e?.message || 'AGENT_LIST_FAILED' }, 401) } })
app.post('/agents/:id/run', async (c) => { try { const { tenant, user } = await requireUser(c); if (!tenant) return c.json({ error: 'TENANT_NOT_FOUND' }, 404); let body: any = {}; try { body = await c.req.json() } catch {} const run = await runAgent({ agentId: c.req.param('id'), tenantId: tenant.id, userId: user.id, input: body.input ?? {}, maxIterations: body.maxIterations }); return c.json({ run }) } catch (e: any) { const code = e?.message === 'UNAUTHORIZED' ? 401 : e?.message === 'AGENT_NOT_FOUND' ? 404 : e?.message === 'INSUFFICIENT_CREDITS' ? 402 : 400; return c.json({ error: e?.message || 'AGENT_RUN_FAILED' }, code) } })
app.post('/agents/:id/stream', async (c) => { try { const { prisma, tenant, user } = await requireUser(c); if (!tenant) return c.json({ error: 'TENANT_NOT_FOUND' }, 404); let body: any = {}; try { body = await c.req.json() } catch {} const agent = await prisma.agent.findFirst({ where: { id: c.req.param('id'), tenantId: tenant.id } }); if (!agent) return c.json({ error: 'AGENT_NOT_FOUND' }, 404); const encoder = new TextEncoder(); const stream = new ReadableStream({ async start(controller) { const send = (event: any) => controller.enqueue(encoder.encode(`data: ${JSON.stringify(event)}\n\n`)); try { await streamAgent({ agent, tenantId: tenant.id, userId: user.id, input: body.input ?? {}, maxIterations: body.maxIterations, memoryLimit: body.memoryLimit }, send); } catch (e: any) { send({ type: 'error', error: e?.message || 'AGENT_STREAM_FAILED' }); } finally { controller.close(); } } }); return new Response(stream, { headers: { 'content-type': 'text/event-stream; charset=utf-8', 'cache-control': 'no-cache, no-transform', connection: 'keep-alive' } }); } catch (e: any) { const code = e?.message === 'UNAUTHORIZED' ? 401 : 400; return c.json({ error: e?.message || 'AGENT_STREAM_FAILED' }, code) } })
app.get('/agents/:id/runs', async (c) => { try { const { prisma, tenant } = await requireUser(c); if (!tenant) return c.json({ runs: [] }); return c.json({ runs: await prisma.agentRun.findMany({ where: { tenantId: tenant.id, agentId: c.req.param('id') }, orderBy: { createdAt: 'desc' }, take: 50 }) }) } catch (e: any) { return c.json({ error: e?.message || 'RUN_LIST_FAILED' }, 401) } })
app.get('/agents/:id/memory', async (c) => { try { const { tenant } = await requireUser(c); const q = c.req.query('q') || ''; return c.json({ memories: q ? await retrieveMemory(c.req.param('id'), tenant.id, q) : await searchMemory(tenant.id, c.req.param('id'), q) }) } catch (e: any) { return c.json({ error: e?.message || 'MEMORY_SEARCH_FAILED' }, 400) } })
app.post('/agents/:id/memory', async (c) => { try { const { tenant } = await requireUser(c); const body: any = await c.req.json(); const memory = await saveMemory(c.req.param('id'), tenant.id, String(body.content || ''), body.metadata || {}); return c.json({ memory }, 201) } catch (e: any) { return c.json({ error: e?.message || 'MEMORY_WRITE_FAILED' }, 400) } })
app.get('/tools', async (c) => { const rl = limited(c, 'tools-list', 120); if (!rl.allowed) return c.json({ error: 'RATE_LIMITED', retryAfter: rl.retryAfter }, 429); return c.json({ tools: listTools() }) })
app.post('/tools/:name/execute', async (c) => { try { const rl = limited(c, `tool:${c.req.param('name')}`, 30); if (!rl.allowed) return c.json({ error: 'RATE_LIMITED', retryAfter: rl.retryAfter }, 429); const { prisma, user, tenant } = await requireUser(c); if (!tenant) return c.json({ error: 'TENANT_NOT_FOUND' }, 404); const tool = getTool(c.req.param('name')); if (!tool) return c.json({ error: 'TOOL_NOT_FOUND' }, 404); const agentId = c.req.header('x-agent-id') || ''; if (!agentId) return c.json({ error: 'AGENT_CONTEXT_REQUIRED' }, 400); const agent = await prisma.agent.findFirst({ where: { id: agentId, tenantId: tenant.id } }); if (!agent) return c.json({ error: 'AGENT_NOT_FOUND' }, 404); const allowedTools = new Set((agent.tools || []).map(String)); if (!allowedTools.has(tool.name)) return c.json({ error: 'TOOL_NOT_ALLOWED' }, 403); validateToolPermission(agent, tool); let body: any = {}; try { body = await c.req.json() } catch {} const result = await executeTool(tool.name, body.input, { tenantId: tenant.id, userId: user.id }); return c.json({ ok: true, result }) } catch (e: any) { const code = e?.message === 'UNAUTHORIZED' ? 401 : e?.message === 'TOOL_NOT_FOUND' ? 404 : e?.message === 'TOOL_NOT_ALLOWED' ? 403 : 400; return c.json({ error: e?.message || 'TOOL_EXECUTION_FAILED' }, code) } })
app.get('/usage', async (c) => { try { const { tenant } = await requireUser(c); if (!tenant) return c.json({ error: 'TENANT_NOT_FOUND' }, 404); return c.json(await getUsage(tenant.id)) } catch (e: any) { return c.json({ error: e?.message || 'USAGE_FAILED' }, 401) } })
app.post('/api-keys', async (c) => { try { const { prisma, tenant, user } = await requireUser(c); let body: any = {}; try { body = await c.req.json() } catch {} const generated = generateApiKey(); const row = await prisma.apiKey.create({ data: { tenantId: tenant.id, userId: user.id, name: String(body.name || 'API Key'), hash: generated.hash, prefix: generated.raw.slice(0, 12) } }); return c.json({ id: row.id, name: row.name, key: generated.raw, prefix: row.prefix }, 201) } catch (e: any) { return c.json({ error: e?.message || 'API_KEY_CREATE_FAILED' }, 400) } })
app.get('/api-keys', async (c) => { try { const { prisma, tenant } = await requireUser(c); const rows = await prisma.apiKey.findMany({ where: { tenantId: tenant.id }, select: { id: true, name: true, prefix: true, createdAt: true, lastUsedAt: true, revokedAt: true }, orderBy: { createdAt: 'desc' } }); return c.json({ keys: rows }) } catch (e: any) { return c.json({ error: e?.message || 'API_KEY_LIST_FAILED' }, 401) })
app.delete('/api-keys/:id', async (c) => { try { const { prisma, tenant } = await requireUser(c); const row = await prisma.apiKey.findFirst({ where: { id: c.req.param('id'), tenantId: tenant.id } }); if (!row) return c.json({ error: 'API_KEY_NOT_FOUND' }, 404); await prisma.apiKey.update({ where: { id: row.id }, data: { revokedAt: new Date() } }); return c.json({ ok: true }) } catch (e: any) { return c.json({ error: e?.message || 'API_KEY_REVOKE_FAILED' }, 404) } })
app.post('/approvals/:id/resolve', async (c) => { try { const { user, tenant } = await requireUser(c); let body: any = {}; try { body = await c.req.json() } catch {} const result = await resolveApproval(tenant.id, user.id, c.req.param('id'), Boolean(body.approved)); return c.json({ approval: result }) } catch (e: any) { return c.json({ error: e?.message || 'APPROVAL_RESOLVE_FAILED' }, 400) } })
app.get('/admin/overview', async (c) => { try { const { prisma, user } = await requireUser(c); if (user.role !== 'ADMIN') return c.json({ error: 'FORBIDDEN' }, 403); const [users, tenants, agents, runs, payments] = await Promise.all([prisma.user.count(), prisma.tenant.count(), prisma.agent.count(), prisma.agentRun.count(), prisma.payment.count()]); return c.json({ users, tenants, agents, runs, payments }) } catch (e: any) { return c.json({ error: e?.message || 'ADMIN_OVERVIEW_FAILED' }, 403) } })
app.onError((err, c) => { console.error(err); return c.json({ error: 'INTERNAL_ERROR' }) })
export default app
